### ISSUE TITLE
Input events crashing the app

### ISSUE THREAD

**Issue by jishan484** [jishan484/PiWebVNC#8]
Currently, only one region is being reused in this app, there is a high probability that the region got invalid.
Based on issue #6, now only one region is being reused.

fix1: check if the region is None.
update: region should not be const.

fix2: fix the existing region if it is none or invalid without assigning a new object to it.

**Comment by jishan484** [comment]
Situation reproduced.
not a region related problem.
- conflicting with input and damage event.
- when the client sends input, a callback function executes input_processor, which needs to be executed as fast as possible.
But that conflicts with other events.

possible solution TBD.

Issue in-hold.

**Comment by jishan484** [comment]
Issue tested.
-> It has been tested that input events are conflicting with damage events. ( probably xtest lib issue or it's a classic multithreaded issue)
#### Changing the issue title
Next Action: try to minimize the conflict using EventLock.
#### Test with a client-side script to automate the random input events.

**Comment by jishan484** [comment]
issue confirmed and successfully reproduced.
```setInterval(()=>{
    webSocket.send("M"+Math.round(Math.random()*700)+" "+Math.round(Math.random()*700));
},30);
```
use this script in the browser.

**Comment by jishan484** [comment]
- [X] tested and merged

- [ ] Stability check

**Comment by 1LineCoder** [comment]
Test complete..

**Comment by 1LineCoder** [comment]
Bug Fixed
